spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888/
      ## 配置名称
      name: config-client
      ## 分支
      label: master
      ## 后缀
      profile: prod

server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://121.36.166.92:1001/eureka/
