spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888/
      name: config-client
      label: master
      profile: dev

server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://121.36.166.92:1001/eureka/
