spring:
  application:
    name: eureka-ribbon

server:
  port: 1003

ribbon:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
      ##http://121.36.166.92:1001/eureka/

